# Generated by Django 5.2.7 on 2026-06-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='block',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
