# Generated by Django 5.2.7 on 2026-06-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_student_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(default='BCA'),
            preserve_default=False,
        ),
    ]
